// Country list for the billing/shipping address "Country" selects on the bema user-edit
// form (docs/decisions/0011-bema-admin.md) — not a claim of exhaustive ISO-3166 coverage,
// just the common set a US-based parcel/cargo shipper to Georgia needs. Add more as real
// customer data surfaces a gap.
export const COUNTRIES = [
  'United States',
  'Georgia',
  'United Kingdom',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Czech Republic',
  'Portugal',
  'Greece',
  'Ireland',
  'Ukraine',
  'Russia',
  'Turkey',
  'Armenia',
  'Azerbaijan',
  'Israel',
  'United Arab Emirates',
  'Saudi Arabia',
  'India',
  'China',
  'Japan',
  'South Korea',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'Australia',
  'New Zealand',
  'South Africa',
].map((name) => ({ value: name, label: name }));
