import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettierConfig from 'eslint-config-prettier';

// Tried eslint-plugin-css-modules for catching kebab-case/camelCase CSS Modules migration
// typos (a `.module.css` class the component never references, or vice versa) — it's
// unmaintained and silently didn't detect anything against our TSX/TypeScript setup, even a
// deliberately broken reference. Using `typed-css-modules` (`bun run css-types`) instead: it
// generates a `.module.css.d.ts` next to each module, so a typo'd `s.foo` is a real
// `tsc`/`next build` type error — see package.json's `css-types`/`predev`/`prebuild` scripts.

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Turns off stylistic ESLint rules that'd conflict with Prettier — Prettier owns
  // formatting, ESLint owns everything else. Must stay last so it can override.
  prettierConfig,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by typed-css-modules (see the note above) — derived, not authored.
    '**/*.module.css.d.ts',
  ]),
]);

export default eslintConfig;
