import cn from 'classnames';

// Wraps the legacy sprite-icon system (`public/css/style.css`'s `i.icon.icon-*` rules,
// still global CSS — see AGENTS.md's "Global CSS cleanup" note; this component doesn't move
// those rules yet, it just gives callers one typed place to reach for an icon instead of
// hand-typing `className="icon icon-whatever"`). `name` is the full set of `icon-*` classes
// that exist in style.css today; add to the union as new ones get used so a typo shows up as
// a type error instead of a silently blank icon.
export type IconName =
  | 'inbox'
  | 'tracking'
  | 'tracking-1'
  | 'tracking-2'
  | 'tracking-3'
  | 'tracking-4'
  | 'tracking-5'
  | 'login'
  | 'menu'
  | 'menusm'
  | 'arr1'
  | 'arr2'
  | 'arr-blue1'
  | 'arr-blue2'
  | 'archarr-l'
  | 'archarr-r'
  | 'phone'
  | 'mail'
  | 'mail-back'
  | 'mail-del'
  | 'mail-markunread'
  | 'mail-next'
  | 'mail-prev'
  | 'mail-reply'
  | 'time'
  | 'search'
  | 'sort'
  | 'edit'
  | 'delete'
  | 'removebig'
  | 'removegrey'
  | 'greyround'
  | 'add'
  | 'ok'
  | 'info'
  | 'notice'
  | 'inprocess'
  | 'calendar'
  | 'map'
  | 'marker-1'
  | 'marker-2'
  | 'marker-3'
  | 'marker-4'
  | 'markerbig'
  | 'play'
  | 'doc'
  | 'discount'
  | 'cashback'
  | 'taxfree'
  | 'onlinestore'
  | 'planeup'
  | 'planedown'
  | 'fb'
  | 'tw'
  | 'gp'
  | 'slider-1'
  | 'slider-2'
  | 'slider-3'
  | 'slider-4'
  | 'whyus-1'
  | 'whyus-2'
  | 'whyus-3'
  | 'whyus-4'
  | 'whyus-5'
  | 'whyus-6'
  | 'whyus-7'
  | 'whyus-8'
  | 'prices-1'
  | 'prices-2'
  | 'prices-3'
  | 'prices-4'
  | 'prices-5'
  | 'prices-6'
  | 'stores-1'
  | 'stores-2'
  | 'stores-3'
  | 'stores-4'
  | 'stores-5'
  | 'stores-6'
  | 'stores-7'
  | 'stores-8'
  | 'stores-9'
  | 'stores-menu-1'
  | 'stores-menu-2'
  | 'stores-menu-3'
  | 'stores-menu-4'
  | 'stores-menu-5'
  | 'stores-menu-6'
  | 'parcel'
  | 'parcel-1'
  | 'parcel-2'
  | 'parcel-3'
  | 'parcel-4'
  | 'parcel-5'
  | 'parcel-6'
  | 'parcel-7'
  | 'parcel-8'
  | 'parcel-9'
  | 'parcel-10'
  | 'parcel-11'
  | 'parcel-alert'
  | 'parcel-gpay'
  | 'parcel-ok'
  | 'parcel-pay';

export function Icon({ name, className, ...props }: { name: IconName } & React.HTMLAttributes<HTMLElement>) {
  return <i className={cn('icon', `icon-${name}`, className)} {...props} />;
}
